apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-pvc
labels:
  type: local 
  name: sonarqube
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
